on:
  push:
    branches:
    - master
name: master
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: sudo apt install pandoc
    - run: npm ci
    - run: npm run whatwg
