on:
  push:
    branches:
    - master
name: master
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: node --version
    - run: sudo apt-get install pandoc
    - run: npm ci
    - run: echo "${{ secrets.CONFIG_JSON }}" | base64 --decode > config.json
    - run: npm run whatwg
    - run: git status
    - uses: actions/checkout@master
      with:
        repository: https://github.com/foolip/reffy-reports.git
        token: ${{ secrets.REFFY_REPORTS_TOKEN }}
        path: reffy-reports
    - run: git status
