on:
  push:
    branches:
    - master
name: master
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Pandoc
      run: sudo apt-get install pandoc
    - name: Install dependencies
      run: npm ci
    - name: Create config.json
      run: echo "$CONFIG_JSON" | base64 --decode > config.json
      env:
        CONFIG_JSON: ${{ secrets.CONFIG_JSON }}
    - name: Crawl
      run: npm run whatwg
